// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4OTrIe13KkCfIA_LlNQ-SqeUP8bPRHpc',
    appId: '1:820990191023:web:d9526a44f6fab7f9fc7b5a',
    messagingSenderId: '820990191023',
    projectId: 'daily-feels-86b10',
    authDomain: 'daily-feels-86b10.firebaseapp.com',
    databaseURL: 'https://daily-feels-86b10-default-rtdb.firebaseio.com',
    storageBucket: 'daily-feels-86b10.appspot.com',
    measurementId: 'G-B83QMGD911',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB35-xvGbFALUBZ5zjFk0yva2lZzVQktpA',
    appId: '1:820990191023:android:b98b09f558c27987fc7b5a',
    messagingSenderId: '820990191023',
    projectId: 'daily-feels-86b10',
    databaseURL: 'https://daily-feels-86b10-default-rtdb.firebaseio.com',
    storageBucket: 'daily-feels-86b10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0erlAhIC0SYvlYaMkuOitwgF2mJVAqcY',
    appId: '1:820990191023:ios:98e35cd2813b1ff5fc7b5a',
    messagingSenderId: '820990191023',
    projectId: 'daily-feels-86b10',
    databaseURL: 'https://daily-feels-86b10-default-rtdb.firebaseio.com',
    storageBucket: 'daily-feels-86b10.appspot.com',
    iosClientId: '820990191023-6hv7i6quqreo7bhghtau2ftcs29fu7vc.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyFeels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0erlAhIC0SYvlYaMkuOitwgF2mJVAqcY',
    appId: '1:820990191023:ios:8060e178c2b7a452fc7b5a',
    messagingSenderId: '820990191023',
    projectId: 'daily-feels-86b10',
    databaseURL: 'https://daily-feels-86b10-default-rtdb.firebaseio.com',
    storageBucket: 'daily-feels-86b10.appspot.com',
    iosClientId: '820990191023-gnvksop8bh1o0jfst1oj9src297rpodn.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailyFeels.RunnerTests',
  );
}
